services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: dev
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mongodb://mongodb:27017/portfolio?replicaSet=rs0
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-nextauth-secret-key-change-this
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
      - NODE_ENV=development
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

  mongodb:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=portfolio
    command: ["--replSet", "rs0", "--bind_ip_all"]

volumes:
  mongodb_dev_data:
    driver: local